# Generated by Django 2.0.2 on 2018-04-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='item',
            field=models.TextField(default='Item', max_length=255),
            preserve_default=False,
        ),
    ]
