# Generated by Django 2.0.2 on 2018-03-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180309_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_amenities', to='api.Amenity'),
        ),
        migrations.AlterField(
            model_name='restaurantamenities',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_amenities', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranthours',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_hours', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='special',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='specials', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='specialhours',
            name='special_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='special_hours', to='api.Special'),
        ),
    ]
