# Generated by Django 2.0.2 on 2018-05-15 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180427_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amenity_details', to='api.Amenity'),
        ),
    ]
