# Generated by Django 2.0.2 on 2018-05-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180515_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Amenity'),
        ),
    ]
