# Generated by Django 2.0.2 on 2018-03-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180309_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='xyz', to='api.Amenity'),
        ),
    ]
