# Generated by Django 2.0.2 on 2018-03-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180309_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Amenity'),
        ),
        migrations.AlterField(
            model_name='restaurantamenities',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Restaurant'),
        ),
    ]
