# Generated by Django 2.0.2 on 2018-03-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180311_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantamenities',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amenities', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_reviews', to='api.Restaurant'),
        ),
    ]
